services:
  web:
    build:
      context: .
      dockerfile: web.dockerfile
    ports:
      - 80:80
    volumes:
      - ./html:/usr/local/apache2/htdocs
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  dbdata:

